src/Entity/Label.php
<?php

namespace App\Entity;

use App\Repository\LabelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LabelRepository::class)]
class Label
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $annee = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $logo = null;

    #[ORM\OneToMany(mappedBy: 'label', targetEntity: Album::class)]
    private Collection $Albums;

    public function __construct()
    {
        $this->Albums = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(int $annee): static
    {
        $this->annee = $annee;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): static
    {
        $this->logo = $logo;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return Collection<int, Album>
     */
    public function getAlbums(): Collection
    {
        return $this->Albums;
    }

    public function addAlbum(Album $album): static
    {
        if (!$this->Albums->contains($album)) {
            $this->Albums->add($album);
            $album->setLabel($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): static
    {
        if ($this->Albums->removeElement($album)) {
            // set the owning side to null (unless already changed)
            if ($album->getLabel() === $this) {
                $album->setLabel(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/LabelController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LabelController extends AbstractController
{
    #[Route('/admin/label', name: 'app_admin_label')]
    public function index(): Response
    {
        return $this->render('admin/label/index.html.twig', [
            'controller_name' => 'LabelController',
        ]);
    }
}

src/Controller/LabelController.php
<?php

namespace App\Controller;

use App\Entity\Label;
use App\Repository\LabelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LabelController extends AbstractController
{
    #[Route('/labels', name: 'app_labels', methods: ["GET","SET"])]
    public function listeLabel(LabelRepository $repo): Response
    {
        $labels = $repo->findall();
        return $this->render('label/listeLabel.html.twig', [
            'controller_name' => 'LabelController',
            'lesLabels' => $labels
        ]);
    }

    #[Route('/label/{id}', name: 'app_label', methods: ["GET","SET"])]
    public function ficheLabel(Label $label): Response
    {
        return $this->render('label/ficheLabel.html.twig', [
            'controller_name' => 'LabelController',
            'unLabel' => $label
        ]);
    }
}

templates/label/ficheLabel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} - {{ unLabel.nom }}{% endblock %}

{% block body %}
{% set nbAlbum = unLabel.albums|length %}
<h1 class="text-center pt-2">Fiche du Label</h1>
<div class="d-flex mb-5">
    <a onclick="javascript:history.back()" class="btn btn-primary text-center w-25">Retour</a>
</div>
<div class="row">
        <div class="card px-0 mb-3 container">
        <div class="card-header">
            <h5 class="card-title text-center">{{ unLabel.nom }} - {{ unLabel.annee }}</h5>
        </div>
        <div class="row py-3 px-1">
            <div class="col d-flex allign-items-center">
                <img style="aspect-ratio: 1/1; width: 192px; margin: auto; object-fit: center;"
                class="rounded"
                src="{{ unLabel.logo }}"
                draggable="false"/>
            </div>
            <div class="pr-3 col">
                 <ul class="list-group list-group-flush">
                    <li class="list-group-item">Nombre d'albums : {{ nbAlbum }}</li>
                    <li class="list-group-item">
                    {{ unLabel.description|u.truncate(200, '...', false)|raw }}
                    </li>
                    <li class="list-group-item">
                        {% if unLabel.type == "Majeur" %}
                        <span class="badge rounded-pill badge-info bg-warning">
                        {% else %}
                        <span class="badge rounded-pill badge-info bg-success">
                        {% endif %}
                        {{unLabel.type}}
                        </span>
                    </li>
                </ul>
            </div>
        </div>

            <div>
                <h5 class="card-title ml-3">Albums signés</h5>
                <table class="table table-sm table-hover table-striped">
                <thead>
                    <tr>
                    <th scope="col" class="col-1">Nom</th>
                    <th scope="col" class="col-3">Artiste</th>
                    <th scope="col" class="col-3">Année</th>
                    <th scope="col" class="col-3">Style</th>
                    </tr>
                </thead>
                    {% for album in unLabel.albums %}
                    {% set artiste = album.artiste %}
                    <tr>
                    <td class="col-6">
                    <a href="{{path('app_album', {'id': album.id})}}">
                        <img src="{{album.image}}" class="rounded mr-2" style="width: 32px; height: 32px;" />{{ album.nom }}
                    </a>
                    </td>
                    <td class="col-4">
                    <a href="{{path('app_artiste', {'id': artiste.id})}}">
                        <img src="{{artiste.image}}" class="rounded mr-2" style="width: 32px; height: 32px;" /> {{ artiste.nom }}
                    </a>
                    </td>
                    <td class="col-1">
                        {{ album.date }}
                    </td>
                    <td class="col-2">
                        <span class="badge rounded-pill badge-info bg-dark">
                            {% for style in album.styles %}
                            {{ style.libelle }}
                            {% endfor %}
                        </span>
                    </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="card-body">
        </div>
</div>
{% endblock %}

templates/label/listeLabel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} - Liste des labels{% endblock %}

{% block body %}
<h1>Liste des Labels</h1>
<div class="gap-3" style="display: grid; grid-template-columns: repeat(4, 1fr);">
    {% for label in lesLabels %}
        {% set nbAlbum = label.albums|length %}
        {% set status = label.type == "Majeur" ? "warning" : "success" %}

        <div class="card" style="">
            <img src=" {{ label.logo }}" class="card-img-top" alt="Logo du label">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ path('app_label', {'id': label.id}) }}">{{label.nom}}</a></h5>
                <h6 class="text-secondary">Depuis {{ label.annee }}</h6>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ nbAlbum }} albums signés</li>
                <li class="list-group-item">
                    Status : {{label.type}}
                </li>
            </ul>
        </div>
    {% endfor %}
</div>
{% endblock %}